### ISSUE TITLE
No Tests Found for Resharper 2017.1, Machine.Specifications.Runner.Resharper for Resharper 2017.1, netcoreapp1.1 project

### ISSUE THREAD

**Issue by derekgreer** [machine/machine.specifications.runner.resharper#55] opened 2017-04-22 23:28 UTC
For a .Net Framework 4.5.2 based project the MSpec VS integration works, but when I create a core project it doesn't.

**Comment by ryudice** [comment] 2017-05-03 18:00
Same issue here

**Comment by ivanz** [comment] 2017-05-08 11:43
This is a dupe of #46 - I am not really sure what's the latest bits that need to be implemented for the runner to support ReSharper's .NET Core support - things have been in flux a lot over the last months.

**Closed by ivanz** 2017-05-08 11:43 UTC
